server:
  port: 8080
  servlet.encoding.force-response: true

spring:
  h2:
    console:
      enable: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver